version: "3.7"

services:
  saltmaster:
    build:
            context: ../saltmaster
            args:
                    salt_repo_url: "https://archive.repo.saltproject.io/yum/redhat/7/x86_64/archive/3000.3.repo"
    image: vrushyash/saltmaster:v2
    restart: always
    networks:
            saltnetworkv2:
                    aliases:
                            - saltmaster
                            - saltmaster.learningv2.com
    
  saltminion1:
    build:
            context: ../saltminion
            args:
                    salt_repo_url: "https://archive.repo.saltproject.io/yum/redhat/7/x86_64/archive/3000.3.repo"
    image: vrushyash/saltminion:v2
    restart: always
    networks:
            saltnetworkv2:
                    aliases:
                            - saltminion1
                            - saltminion1.learningv2.com

  saltminion2:
    build:
            context: ../saltminion
            args:
                    salt_repo_url: "https://archive.repo.saltproject.io/yum/redhat/7/x86_64/archive/3000.3.repo"
    image: vrushyash/saltminion:v2
    restart: always
    networks:
            saltnetworkv2:
                    aliases:
                            - saltminion2
                            - saltminion2.learningv2.com



networks:
        saltnetworkv2:

